### ISSUE TITLE
How is it different from clap and docopt?

### ISSUE THREAD

**Issue by zitsen** [mattforni/args#1]
Since there's other popular command line parsers like 
- [clap](https://crates.io/crates/clap) - A full featured, fast Command Line Argument Parser for Rust
- [DocOpt](https://crates.io/crates/docopt) - Docopt for Rust (command line argument parser).

How is your crate different from them? I think explaination of such question in README would be helpful for others.

**Comment by mattforni** [comment]
Truthfully, It's not all that different, but it allows ease of use. Have you tried using it?
